export const LOGIN_START = 'LOGIN_START';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_CLEANUP = 'LOGIN_CLEANUP';

export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_CLEANUP = 'SIGNUP_CLEANUP';

export const GET_POSTS_START = 'GET_POSTS_START';
export const GET_POSTS_FAIL = 'GET_POSTS_FAIL';
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const GET_POSTS_CLEANUP = 'GET_POSTS_CLEANUP';
